Algoritmo "ListaDeCompras"
// Descrição   : Cadastrar e imprimir uma lista de compras usando um vetor
// Autor(a)    : Luiza Pereira Silva

numero: vetor[0..20] de inteiro
listacompras: vetor [0..20] de caracter
x: inteiro

Inicio

para x de 0 ate 4 faca
     escreval("Digite o ", (x+1),"item da lista de compras:")
     leia (listacompras[x])

fimpara

para x de 0 ate 4 faca

     escreval("Item", x+1 ", listacompras[x]")

fimpara

Fimalgoritmo